### ISSUE TITLE
`property` with ex_unit context binding

### ISSUE THREAD

**Issue by jtmoulia** [parroty/excheck#6]
Hey, it'd be useful if an excheck `property` could accept the [ExUnit.Case context](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/case.ex#L30).

For example:

```elixir
property :foo, %{bar: baz} do
  ...
end
```

I hate to admit it, but I tried and failed to pull this off by following [ex_unit's example](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/case.ex#L203). S'pose I should read that metaprogramming elixir book.

**Comment by parroty** [comment]
Thanks for the comment. I'll be looking into it.

**Comment by parroty** [comment]
I tried to refer the context variable from the ExUnit, though I'm not confident. Does this make sense?

**Comment by jtmoulia** [comment]
Perfect. Thanks for the help and for excheck -- I love using it.

**Comment by parroty** [comment]
Thanks! Any feedbacks are appreciated, as I'm yet at learning step about property-based testing.

**Comment by herenowcoder** [comment]
Mmm I just started to need this one. Thx for implementing! [:

**Comment by herenowcoder** [comment]
Can you also publish v0.2.2 containing this to Hex?

**Comment by parroty** [comment]
I think this one is included in the v0.2.1.

**Comment by herenowcoder** [comment]
Ahh now I see. You're right [:

The misunderstanding comes from how people version things.
One strict semver way is putting 0.42.1 into mix *only* when it really becomes this ver, tagging it, and immediately starting with 0.42.2-dev.

This has an advantage that a commit where the ver is switched is also a point where it really is this new ver - handy for people looking at your commits.

The other, more relaxed way, is after releasing v0.42.1 mark new ver as 0.42.2. Still one information is lost -- that this is in-development version -- in fact not lost but requires scanning through commits history in order to grasp it, instead of just having one look into mix.exs or whatever thing which provides version number.

Just 3cents [:

**Comment by parroty** [comment]
> One strict semver way is putting 0.42.1 into mix only when it really becomes this ver, tagging it, and immediately starting with 0.42.2-dev.
I am seeing the elixir is taking this approach, but I'm thinking a little too much for small number of commit ones. 
> The other, more relaxed way, is after releasing v0.42.1 mark new ver as 0.42.2. 
I'm taking this one (mainly for not forgetting incrementing version...), and the tag is matched with hex-release.

**Comment by herenowcoder** [comment]
Ok, thx for the clarification!
